all: step1.c step3.c step5.c step6.c step7.c step8.c
	gcc -o step1 step1.c
	gcc -o step3 step3.c
	gcc -o step5 step5.c
	gcc -o step6 step6.c
	gcc -o step7 step7.c
	gcc -o step8 step8.c -lpthread

clean:; rm -f step1 step3 step5 step6 step7 step8
